name: CI/CD Flask Docker
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cd:
    name: Docker Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem
          # We use a backslash \ to ensure the command continues on the next line correctly
          ssh -i key.pem -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
          "powershell -ExecutionPolicy Bypass -File 'C:\Users\Moham\Documents\DOCKER\deploy.ps1' -DockerUser ${{ secrets.DOCKERHUB_USERNAME }} -DockerToken ${{ secrets.DOCKERHUB_TOKEN }}"